In [1]:
import torch
import torch.nn as nn

In [7]:
# 输入数据
input = torch.randn(3, 2)
print(input)
# 得到预测概率值
pred = torch.sigmoid(input)
print(pred)

tensor([[ 1.9818, -0.0140],
        [ 0.1873, -0.6416],
        [ 0.0104,  0.8937]])
tensor([[0.8789, 0.4965],
        [0.5467, 0.3449],
        [0.5026, 0.7096]])


In [24]:
# 目标值
target = torch.tensor([[0,1],[1,0],[0,1]], dtype=torch.float)
print(target)

tensor([[0., 1.],
        [1., 0.],
        [0., 1.]])


In [25]:
# 定义损失函数
loss = nn.BCELoss()
print(loss(pred, target))

tensor(0.8132)
