In [1]:
import numpy as np

In [18]:
# 定义向量
x = np.array([2, 5, 8])
print(x)
print(x.shape)

x1 = np.array([[2, 5, 8], [12, 15, 18]])
print(x1)
print(x1.shape)
print(x1.T)
print(x1.T.shape)
x1 = np.array([[2 ,  5 ,  8]])
print(x1)
print(x1.shape)
print(x1.T)
print(x1.T.shape)

[2 5 8]
(3,)
[[ 2  5  8]
 [12 15 18]]
(2, 3)
[[ 2 12]
 [ 5 15]
 [ 8 18]]
(3, 2)
[[2 5 8]]
(1, 3)
[[2]
 [5]
 [8]]
(3, 1)


In [17]:
# 1. 向量转置
print(x.T)
print(x.T.shape)

[2 5 8]
(3,)


In [4]:
# 2. 相加
y = np.array([1, 3, 7])
print(x + y)

[ 3  8 15]


In [5]:
# 3. 向量与标量相乘
print(x * 3)

[ 6 15 24]


In [6]:
# 4. 向量与向量相乘（对应位置元素相乘）
print(x * y)

[ 2 15 56]


In [7]:
# 5. 向量点乘
np.dot(x, y)
print(x.dot(y))

73


In [8]:
print(x @ y)

73


In [24]:
# 6. 计算范数
l0_norm = np.linalg.norm(x, ord=0)
print(l0_norm)
l1_norm = np.linalg.norm(x, ord=1)
print(l1_norm)

3.0
15.0


In [23]:
l2_norm = np.linalg.norm(x, ord=2)
print(l2_norm)

9.643650760992955
