In [1]:
import numpy as np

In [2]:
A = np.array([[1, 1], [2, 2], [0, 0]])

U, S, V = np.linalg.svd(A)

print(U)
print(S)
print(V)

[[-0.4472136  -0.89442719  0.        ]
 [-0.89442719  0.4472136   0.        ]
 [ 0.          0.          1.        ]]
[3.16227766e+00 8.22677308e-17]
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]


In [3]:
from sklearn.utils.extmath import randomized_svd

In [4]:
U, S, V = randomized_svd(A, n_components=2)
print(U)
print(S)
print(V)

[[ 0.4472136   0.89442719]
 [ 0.89442719 -0.4472136 ]
 [ 0.         -0.        ]]
[3.16227766e+00 1.62596948e-32]
[[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]


In [5]:
from sklearn.decomposition import PCA

In [6]:
X = np.random.randn(100, 3)
print(X)
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X)
print(X_pca.shape)
print(X_pca)

[[-2.33783356e-01  7.00670375e-01 -1.49744762e+00]
 [-1.37920820e+00 -1.83910471e+00 -1.00910334e+00]
 [ 1.14058434e-01 -8.63314338e-01 -1.80055833e+00]
 [ 7.59311484e-02  1.11270958e-01  1.01549219e+00]
 [ 1.22300943e+00 -9.45238591e-01  6.23811849e-01]
 [-2.40121575e+00  7.93533159e-02 -6.58999441e-01]
 [-3.59512750e-01  1.29596376e+00 -1.80835526e+00]
 [-5.88301088e-01  3.39424221e-01  1.10001061e+00]
 [ 9.15787595e-01  7.92991839e-01 -1.02823948e+00]
 [-1.56628677e+00 -1.93073310e+00 -2.11442243e-01]
 [ 2.30421025e+00  9.76108674e-02 -1.51746786e+00]
 [ 1.08007025e+00 -7.92901884e-01 -2.66620462e+00]
 [-1.29883232e+00 -2.01251736e+00  5.85496761e-01]
 [-2.51316692e-01 -2.62733631e-02 -9.34097763e-01]
 [ 1.37302476e+00  3.30363896e-01 -2.74493452e+00]
 [ 3.32851706e-01  1.02617133e+00  6.67190799e-01]
 [-1.78484161e+00  1.23430056e-01 -1.41219150e-01]
 [-5.83226631e-01  6.76322490e-01  5.85877661e-01]
 [-8.35106533e-01  3.31314799e-01 -1.44556219e+00]
 [-1.31606542e+00 -3.62873306e-